# Generated by Django 4.2 on 2025-11-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_inr',
            field=models.IntegerField(default=0, help_text='Price in INR (0 = free)'),
        ),
    ]
