# Generated by Django 4.2 on 2025-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_price_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_inr',
            field=models.IntegerField(default=0, help_text='Enter course price in INR'),
        ),
    ]
